name: Publish Nuget Packages
on:
  workflow_dispatch:

jobs:
  build-test-publish:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.update.outputs.newVersion }}
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Bump version (local only)
        id: update
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: |
            "**/*.csproj", "**/*.nuspec", "**/AssemblyInfo.cs"
          version: bump-build

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
        continue-on-error: true

      - name: Pack
        run: dotnet pack -c Release --no-build -o ./nupkgs

      - name: Publish to NuGet.org
        run: dotnet nuget push "./nupkgs/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate

      - name: Publish to GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/gunpal5/index.json" --name github --username gunpal5 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          dotnet nuget push "./nupkgs/*.nupkg" --source github --skip-duplicate

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.update.outputs.newVersion }}
          name: v${{ steps.update.outputs.newVersion }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  commit-version:
    name: Commit Version Bump
    needs: [build-test-publish]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump version
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: |
            "**/*.csproj", "**/*.nuspec", "**/AssemblyInfo.cs"
          version: bump-build

      - name: Commit and push
        run: |
          git config user.name "Gunpal Jain"
          git config user.email "gunpal5@gmail.com"
          git add .
          git commit -m "Bump version to v${{ needs.build-test-publish.outputs.new_version }}"
          git push
